import globals from "globals";
import pluginJs from "@eslint/js";
import pluginReact from "eslint-plugin-react";
import pluginReactHooks from "eslint-plugin-react-hooks";
import pluginUnusedImports from "eslint-plugin-unused-imports";

/**
 * Flat config, composed as an array rather than one merged object.
 *
 * The previous version was a single object that did this:
 *
 *     { ...pluginJs.configs.recommended,
 *       ...pluginReact.configs.flat.recommended,
 *       languageOptions: {...}, rules: {...} }
 *
 * Object spread merges keys, not rule tables. Both presets carry a `rules`
 * key, so react's overwrote js's outright — and then the explicit `rules` at
 * the bottom overwrote react's. The net effect was that neither preset applied
 * at all: the entire lint gate was the eight rules written by hand.
 *
 * That is not a style quibble. Measured on a probe file, `eslint . --quiet`
 * exited 0 on code containing an undeclared global, a `debugger` statement and
 * a duplicated switch case. CI has a Lint step; it was checking for unused
 * imports and very little else.
 *
 * Flat config's actual composition mechanism is the array — later entries add
 * to earlier ones for the files they match. Presets go in as their own
 * elements; project rules follow and win where they overlap.
 */
export default [
  {
    // Global ignores. Must be an entry carrying only `ignores` to apply
    // repo-wide rather than to one `files` glob.
    ignores: ["dist/**", "node_modules/**", "public/**", ".wrangler/**"],
  },

  // Core JS correctness rules — no-undef, no-dupe-keys, no-unreachable and the
  // rest of the set that was silently absent.
  pluginJs.configs.recommended,

  {
    /**
     * Browser source.
     *
     * The old `files` list was src/components, src/pages and a src/Layout.jsx
     * that has not existed for some time — and `ignores` then removed
     * src/lib/**. So src/App.jsx, src/main.jsx, every hook in src/hooks and the
     * whole of src/lib were linted by nothing at all. src/lib is where the auth
     * context, the Supabase client, the upload path and the error taxonomy
     * live: the files where an undeclared identifier costs the most.
     *
     * src/components/ui/** is still relaxed, in its own entry below — it is
     * vendored shadcn output, not code we author — but it is no longer skipped.
     */
    files: ["src/**/*.{js,mjs,cjs,jsx}"],
    ignores: ["src/**/*.test.mjs"],
    ...pluginReact.configs.flat.recommended,
    languageOptions: {
      globals: {
        ...globals.browser,
        // Replaced at build time by vite.config.js `define`. Declared readonly
        // so a stray assignment is still an error — it is a constant baked into
        // the bundle, not a variable.
        __SENTRY_RELEASE__: "readonly",
      },
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    settings: {
      react: {
        version: "detect",
      },
    },
    plugins: {
      react: pluginReact,
      "react-hooks": pluginReactHooks,
      "unused-imports": pluginUnusedImports,
    },
    rules: {
      // Superseded by unused-imports/no-unused-vars below, which understands
      // JSX-only references. Leaving both on double-reports every component.
      "no-unused-vars": "off",

      "react/jsx-uses-vars": "error",
      "react/jsx-uses-react": "error",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "warn",
        {
          vars: "all",
          varsIgnorePattern: "^_",
          args: "after-used",
          argsIgnorePattern: "^_",
        },
      ],

      "react/prop-types": "off",
      "react/react-in-jsx-scope": "off",
      "react/no-unknown-property": [
        "error",
        { ignore: ["cmdk-input-wrapper", "toast-close"] },
      ],

      "react-hooks/rules-of-hooks": "error",
      /**
       * Warn rather than error, and that is a staging decision rather than an
       * opinion about the rule.
       *
       * This is the rule that catches the stale-closure class of bug — an
       * effect that reads `sessionId` but does not list it, so it keeps acting
       * on the split the user was looking at two screens ago. This app polls,
       * subscribes and confirms payments; it is exactly the codebase the rule
       * exists for.
       *
       * It has never run here, so promoting it straight to "error" fails CI on
       * a backlog nobody has triaged, and the reflex fix — pasting in whatever
       * the rule names — introduces render loops wherever the missing dep is an
       * unmemoised object. Warn now, so the count is visible through
       * `npm run lint:report`; promote to error once it reads zero.
       */
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  {
    /**
     * Vendored shadcn/ui primitives. Generated by the CLI and updated by
     * regenerating, so style findings here are not actionable — but the file
     * set is no longer skipped outright, which is what catches a botched
     * hand-edit to a primitive every screen depends on.
     */
    files: ["src/components/ui/**/*.{js,jsx}"],
    rules: {
      "react/display-name": "off",
      "react/prop-types": "off",
      "react-hooks/exhaustive-deps": "off",
      "unused-imports/no-unused-vars": "off",
    },
  },

  {
    /**
     * Worker and shared modules run in Node or on Cloudflare, where `window`
     * does not exist and `process` does. Linting them with browser globals is
     * how `process.env` gets reported as undefined and the whole directory gets
     * excluded instead of fixed.
     */
    files: ["worker/**/*.js", "shared/**/*.js"],
    languageOptions: {
      globals: { ...globals.node, ...globals.serviceworker },
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: "module",
      },
    },
    rules: {
      /**
       * `const { host_key_hash, ...rest } = session` is how this codebase strips
       * a field it must never serialise — see publicSession in
       * worker/routes/functions.js, and the undo branch that drops paid_amount
       * and paid_at. The binding is unused on purpose; that is the entire point
       * of writing it.
       *
       * Without ignoreRestSiblings the rule reports the safest line in the file
       * and teaches people to delete it.
       */
      "no-unused-vars": ["error", { ignoreRestSiblings: true, argsIgnorePattern: "^_" }],
    },
  },

  {
    /**
     * Build and tooling scripts. These are Node programs that also drive a real
     * browser: everything inside a Playwright `page.evaluate()` callback is
     * serialised and executed in the page, so `document`, `window` and
     * `localStorage` are legitimately in scope there even though the file runs
     * under Node. Both global sets, or the prerender and browser-suite drivers
     * report ~60 phantom no-undefs.
     *
     * export-from-browser.js is not run by Node at all — it is a snippet meant
     * to be pasted into a browser console — and is covered by the same entry.
     */
    files: ["scripts/**/*.{js,mjs}"],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: "module",
      },
    },
    rules: {
      "no-unused-vars": ["error", { ignoreRestSiblings: true, argsIgnorePattern: "^_" }],
    },
  },

  {
    /**
     * Build configuration, which runs in Node and not in a browser.
     *
     * vite.config.js reads process.env — SENTRY_AUTH_TOKEN, SENTRY_ORG, the
     * release name — to decide whether sourcemaps are generated and uploaded.
     * Without this it is parsed as browser code and `process` is five undefined
     * globals, which is a lint failure describing nothing real.
     */
    files: ["vite.config.js", "postcss.config.js"],
    languageOptions: {
      globals: globals.node,
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: "module",
      },
    },
  },

  {
    /**
     * tailwind.config.js alone. package.json declares "type": "module", so
     * every other root config here is ESM — this one file still uses
     * `module.exports` and `require`, which the default ESM parse reports as
     * two undefined globals. Matching `*.config.js` instead would flip
     * vite/postcss/eslint's own config to CommonJS and fail them at parse.
     */
    files: ["tailwind.config.js"],
    languageOptions: {
      globals: globals.node,
      sourceType: "commonjs",
      parserOptions: {
        ecmaVersion: 2022,
      },
    },
  },

  {
    // Node's built-in test runner. `describe`/`it` arrive via node:test imports,
    // but these files touch Node and browser globals throughout.
    files: ["**/*.test.mjs"],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: "module",
      },
    },
    rules: {
      "no-unused-vars": "off",
    },
  },
];
